import {deepseekTitleCompletion} from "../agent/deepseekClient";
import type {ChatMessage} from "../agent/types";
import type {PersistedSettings} from "../settings/types";
import type {ChatSession} from "./types";
import {userMessagePlainText} from "./storage";

const MAX_TITLE_LEN = 20;
const SNIPPET_LEN = 600;

const TITLE_SYSTEM_PROMPT =
    "你是会话标题生成器。根据用户的首条消息，输出一个简短中文标题。" +
    "要求：不超过 15 个字；不要引号、书名号或标点结尾；不要解释；只输出标题本身。";

function snippet(text: string, maxLen: number): string {
    const t = text.trim().replace(/\s+/g, " ");
    if (!t) {
        return "";
    }
    return t.length > maxLen ? `${t.slice(0, maxLen)}…` : t;
}

export interface SessionTitleInput {
    userText: string;
    composerDoc?: ChatMessage["composerDoc"];
}

function resolveUserPlainText(input: SessionTitleInput): string {
    const doc = input.composerDoc;
    if (doc && typeof doc === "object" && (doc as {type?: string}).type === "doc") {
        const fromDoc = userMessagePlainText({role: "user", content: null, composerDoc: doc});
        if (fromDoc.trim()) {
            return fromDoc;
        }
    }
    return input.userText.trim();
}

function buildTitlePrompt(input: SessionTitleInput): string | null {
    const userText = snippet(resolveUserPlainText(input), SNIPPET_LEN);
    if (!userText) {
        return null;
    }
    return `用户：${userText}`;
}

export function normalizeGeneratedTitle(raw: string): string {
    let t = raw.trim().replace(/\s+/g, " ");
    t = t.replace(/^[\s"'「『【《]+|[\s"'」』】》]+$/g, "");
    t = t.replace(/[。．.!！?？:：;；,，、]+$/g, "");
    if (!t) {
        return "";
    }
    return t.length > MAX_TITLE_LEN ? t.slice(0, MAX_TITLE_LEN) : t;
}

/** 首条用户消息发送时并行生成标题（仅一次） */
export function shouldAutoSummarizeSessionTitle(sess: ChatSession): boolean {
    if (sess.titleAutoGenerated) {
        return false;
    }
    const userCount = sess.messages.filter((m) => m.role === "user").length;
    return userCount === 0;
}

export async function generateSessionTitle(
    settings: Pick<PersistedSettings, "baseUrl" | "apiKey" | "model">,
    input: SessionTitleInput,
    model: string,
    signal?: AbortSignal,
): Promise<string | null> {
    if (!settings.apiKey?.trim()) {
        return null;
    }
    const prompt = buildTitlePrompt(input);
    if (!prompt) {
        return null;
    }
    const raw = await deepseekTitleCompletion(
        {baseUrl: settings.baseUrl, apiKey: settings.apiKey, model},
        TITLE_SYSTEM_PROMPT,
        prompt,
        signal,
    );
    if (!raw) {
        return null;
    }
    const title = normalizeGeneratedTitle(raw);
    return title || null;
}
